# Generated by Django 5.2.8 on 2025-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.CharField(default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
