# Generated by Django 5.2.8 on 2025-11-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_group_game_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='flag_url',
        ),
        migrations.AddField(
            model_name='team',
            name='country_code',
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 code (e.g., 'ES' for Spain, 'DK' for Denmark)", max_length=2, null=True),
        ),
    ]
