# Generated by Django 5.2.8 on 2025-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_team_flag_url_team_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguess',
            name='guess_away',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userguess',
            name='guess_home',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
