# Generated by Django 6.0 on 2025-12-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bonuschoices_bonusquestion_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
